balkanistan_accueil:
  path: /accueil
  controller: App\Controller\BalkanistanController::accueil

mairie_accueil:
  path: /mairie
  controller: App\Controller\MairieController::accueil

mairie_navigation:
  path: /mairie/navigation
  controller: App\Controller\MairieController::navigation

mairie_afficher: #Plus nécessaire
  path: /afficher/{numero}
  controller: App\Controller\MairieController::afficher
  requirements:
    numero: '\d{1,2}'

mairie_voir:
  path: /mairie/voir/{id}
  controller: App\Controller\MairieController::voir
  requirements:
    numero: \d+

mairie_ajouter:
  path: /mairie/ajouter/{ville}
  controller: App\Controller\MairieController::ajouter
  requirements:
    ville: "[a-zA-Z]{1,50}"

mairie_ajouter2:     
  path:  /mairie/ajouter2    
  controller: App\Controller\MairieController::ajouter2

#mairie_modifier:     #On ne modifie pas les mairies
#  path:  /mairie/modifier    
#  controller: App\Controller\MairieController::modifier

mairie_amiens:
 path: /amiens
 controller: App\Controller\MairieController::amiens

parti_accueil:
  path: /Parti
  controller: App\Controller\PartiController::accueil

politicien_accueil:
  path: /Politicien
  controller: App\Controller\PoliticienController::accueil

affaire_accueil:
  path: /Affaire
  controller: App\Controller\AffaireController::accueil