balkanistan_index:
  path: /
  controller: App\Controller\BalkanistanController::accueil

balkanistan_accueil:
  path: /accueil
  controller: App\Controller\BalkanistanController::accueil

mairie_accueil:
  path: /mairie
  controller: App\Controller\MairieController::accueil

mairie_navigation:
  path: /mairie/navigation
  controller: App\Controller\MairieController::navigation

mairie_afficher: #Plus nécessaire
  path: /mairie/afficher/{numero}
  controller: App\Controller\MairieController::afficher
  requirements:
    numero: '\d{1,2}'

mairie_voir:
  path: /mairie/voir/{id}
  controller: App\Controller\MairieController::voir
  requirements:
    numero: \d+

mairie_ajouter:
  path: /mairie/ajouter/{ville}
  controller: App\Controller\MairieController::ajouter
  requirements:
    ville: "[a-zA-Z]{1,50}"

mairie_ajouter2:     
  path:  /mairie/ajouter2    
  controller: App\Controller\MairieController::ajouter2

#mairie_modifier:     #On ne modifie pas les mairies
#  path:  /mairie/modifier    
#  controller: App\Controller\MairieController::modifier

mairie_amiens:
 path: /amiens
 controller: App\Controller\MairieController::amiens

parti_accueil:
  path: /Parti
  controller: App\Controller\PartiController::accueil

parti_navigation:
  path: /parti/navigation
  controller: App\Controller\PartiController::navigation

parti_voir:
  path: /parti/voir/{id}
  controller: App\Controller\PartiController::voir
  requirements:
    numero: \d+

parti_ajouter:
  path: /parti/ajouter/{nom}
  controller: App\Controller\PartiController::ajouter
  requirements:
    nom: "[a-zA-Z]{1,50}"

parti_ajouter2:     
  path:  /parti/ajouter2    
  controller: App\Controller\PartiController::ajouter2

parti_supprimer:     
  path:  /parti/supprimer/{id}   
  controller: App\Controller\PartiController::supprimer

politicien_accueil:
  path: /Politicien
  controller: App\Controller\PoliticienController::accueil

politicien_navigation:
  path: /politicien/navigation
  controller: App\Controller\PoliticienController::navigation

politicien_voir:
  path: /politicien/voir/{id}
  controller: App\Controller\PoliticienController::voir
  requirements:
    numero: \d+

politicien_ajouter:
  path: /politicien/ajouter/{nom}
  controller: App\Controller\PoliticienController::ajouter
  requirements:
    nom: "[a-zA-Z]{1,50}"

politicien_ajouter2:     
  path:  /politicien/ajouter2    
  controller: App\Controller\PoliticienController::ajouter2

politicien_modifier:
  path:  /politicien/modifier/{id}
  controller: App\Controller\PoliticienController::modifier
  requirements:
    id: \d+

politicien_modifier_suite:
  path: /politicien/modifierSuite/{id}
  controller: App\Controller\PoliticienController::modifierSuite
  methods: POST

politicien_supprimer:
  path: /politicien/supprimer/{id}
  controller: App\Controller\PoliticienController::supprimer
  requirements:
    numero: \d+

affaire_accueil:
  path: /Affaire
  controller: App\Controller\AffaireController::accueil

affaire_navigation:
  path: /affaire/navigation
  controller: App\Controller\AffaireController::navigation

affaire_voir:
  path: /affaire/voir/{id}
  controller: App\Controller\AffaireController::voir
  requirements:
    numero: \d+

affaire_ajouter:
  path: /affaire/ajouter/{nom}
  controller: App\Controller\AffaireController::ajouter
  requirements:
    nom: "[a-zA-Z]{1,50}"

affaire_ajouter2:     
  path:  /affaire/ajouter2    
  controller: App\Controller\AffaireController::ajouter2

affaire_modifier:
  path:  /affaire/modifier/{id}
  controller: App\Controller\AffaireController::modifier
  requirements:
    id: \d+

affaire_modifier2:
  path:  /affaire/modifier2/{id}
  controller: App\Controller\AffaireController::modifier2
  requirements:
    id: \d+

affaire_modifier_suite:
  path: /affaire/modifierSuite/{id}
  controller: App\Controller\AffaireController::modifierSuite
  methods: POST